library(readr)
WIKI <- read_csv("C:/Users/welcome/Desktop/WIKI.csv") #loading file
View(WIKI)
WIKI$Exp5<- as.numeric(WIKI$Exp5) #changing columns to numeric
WIKI$Exp4<- as.numeric(WIKI$Exp4)
WIKI$Exp3<- as.numeric(WIKI$Exp3)
WIKI$Exp2<- as.numeric(WIKI$Exp2)
WIKI$Exp1<- as.numeric(WIKI$Exp1)
WIKI$Inc1<- as.numeric(WIKI$Inc1)
WIKI$Inc2<- as.numeric(WIKI$Inc2)
WIKI$Inc3<- as.numeric(WIKI$Inc3)
WIKI$Inc4<- as.numeric(WIKI$Inc4)
WIKI$BI1 <- as.numeric(WIKI$BI1)
WIKI$BI2 <- as.numeric(WIKI$BI2)
WIKI$JR1 <- as.numeric(WIKI$JR1)
WIKI$JR2 <- as.numeric(WIKI$JR2)
WIKI$Pf1<- as.numeric(WIKI$Pf1)
WIKI$Pf2<- as.numeric(WIKI$Pf2)
WIKI$Pf3<- as.numeric(WIKI$Pf3)
WIKI$Use1 <- as.numeric(WIKI$Use1)
WIKI$Use2 <- as.numeric(WIKI$Use2)
WIKI$Use3 <- as.numeric(WIKI$Use3)
WIKI$Use4 <- as.numeric(WIKI$Use4)
WIKI$Use5 <- as.numeric(WIKI$Use5)
WIKI$SA1 <- as.numeric(WIKI$SA1)
WIKI$SA2 <- as.numeric(WIKI$SA2)
WIKI$SA3 <- as.numeric(WIKI$SA3)
WIKI$Im1 <- as.numeric(WIKI$Im1)
WIKI$Im2 <- as.numeric(WIKI$Im2)
WIKI$Im3 <- as.numeric(WIKI$Im3)
WIKI$Vis1 <- as.numeric(WIKI$Vis1)
WIKI$Vis2 <- as.numeric(WIKI$Vis2)
WIKI$Vis3 <- as.numeric(WIKI$Vis3)
WIKI$Qu1 <- as.numeric(WIKI$Qu1)
WIKI$Qu2 <- as.numeric(WIKI$Qu2)
WIKI$Qu3 <- as.numeric(WIKI$Qu3)
WIKI$Qu4 <- as.numeric(WIKI$Qu4)
WIKI$Qu5<- as.numeric(WIKI$Qu5)
WIKI$ENJ1<- as.numeric(WIKI$ENJ1)
WIKI$ENJ2<- as.numeric(WIKI$ENJ2)
WIKI$PEU1<- as.numeric(WIKI$PEU1)
WIKI$PEU2<- as.numeric(WIKI$PEU2)
WIKI$PEU3<- as.numeric(WIKI$PEU3)
WIKI$PU1<- as.numeric(WIKI$PU1)
WIKI$PU2<- as.numeric(WIKI$PU2)
WIKI$PU3<- as.numeric(WIKI$PU3)
WIKI$DOMAIN<- as.numeric(WIKI$DOMAIN)
WIKI$YEARSEXP<- as.numeric(WIKI$YEARSEXP)
WIKI$OTHERSTATUS<- as.numeric(WIKI$OTHERSTATUS)
WIKI$UOC_POSITION<- as.numeric(WIKI$UOC_POSITION)
WIKI$OTHER_POSITION<- as.numeric(WIKI$OTHER_POSITION)
WIKI$USERWIKI<- as.numeric(WIKI$USERWIKI)
summary(WIKI)
WIKI[is.na(WIKI)] <- 0 #NA to 0
wss <- numeric(15)
for (k in 1:15) wss [k] <- sum (kmeans (WIKI, centers=k, nstart=25)$withinss)
plot(1:15, wss, type='b', xlab='Number of Clusters', ylab='Within Sum of Squares') #plotting for selecting number of clusters
km<-kmeans(WIKI,4)
km
x=WIKI 
cl=(kmeans(x,4)) 
x$cluster=factor(cl$cluster) 
centers=as.data.frame(cl$centers) 
install.packages("ggplot2")
library(ggplot2)
g1=ggplot(data=x, aes(x=UOC_POSITION, y=PU1,)) + geom_point() + theme(legend.position="right") + geom_point(data=centers, aes(x=UOC_POSITION,y=PU1)) + geom_point(data=centers, aes(x=UOC_POSITION,y=PU1), color=as.factor(c(1,2,3,4)), size=50, alpha=.3, show.legend=FALSE)
g2=ggplot(data=x, aes(x=UOC_POSITION, y=PU2,)) + geom_point() + theme(legend.position="right") + geom_point(data=centers, aes(x=UOC_POSITION,y=PU2)) + geom_point(data=centers, aes(x=UOC_POSITION,y=PU2), color=as.factor(c(1,2,3,4)), size=50, alpha=.3, show.legend=FALSE)
g3=ggplot(data=x, aes(x=UOC_POSITION, y=PU3,)) + geom_point() + theme(legend.position="right") + geom_point(data=centers, aes(x=UOC_POSITION,y=PU3)) + geom_point(data=centers, aes(x=UOC_POSITION,y=PU3), color=as.factor(c(1,2,3,4)), size=50, alpha=.3, show.legend=FALSE)
install.packages("gridExtra")
library("gridExtra") #plotting data with clusters
grid.arrange(arrangeGrob(g1 + theme(legend.position="none"),g2 + theme(legend.position="none"),g3 + theme(legend.position= "none "),top ="Wikipedia Perceived Usefulness Cluster Analysis",ncol=1))